version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    reviewers:
      - Adacchi3
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
    reviewers:
      - Adacchi3
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
